version: '3.9'
services:
  metrics:
    container_name: metrics
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - './app/:/app'
    env_file:
      - .env

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "8001:9090"
    volumes:
      - './prometheus/:/etc/prometheus'
  
  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 8002:3000
